SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `pv` (
  `IDPv` int(11) NOT NULL AUTO_INCREMENT,
  `NomPv` varchar(200) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`IDPv`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT AUTO_INCREMENT=2 ;

CREATE TABLE IF NOT EXISTS `pv_groupes` (
  `IDPv` int(11) NOT NULL,
  `IDGroupes` int(11) NOT NULL,
  PRIMARY KEY (`IDPv`,`IDGroupes`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

CREATE TABLE IF NOT EXISTS `pv_libelles` (
  `IDLibelles` int(11) NOT NULL AUTO_INCREMENT,
  `Libelle` text CHARACTER SET utf8 NOT NULL,
  `IDSujet` int(11) NOT NULL,
  `DateLibelle` date NOT NULL,
  `RespLibelle` varchar(100) CHARACTER SET utf8 NOT NULL,
  `DelaiLibelle` varchar(50) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`IDLibelles`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT AUTO_INCREMENT=1619 ;

CREATE TABLE IF NOT EXISTS `pv_offices` (
  `IDPv` int(11) NOT NULL,
  `IDOffice` int(11) NOT NULL,
  PRIMARY KEY (`IDPv`,`IDOffice`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

CREATE TABLE IF NOT EXISTS `pv_sujets` (
  `IDSujet` int(11) NOT NULL AUTO_INCREMENT,
  `NomSujet` varchar(200) NOT NULL,
  `IDTheme` int(11) NOT NULL,
  `ActifSujet` int(11) NOT NULL,
  PRIMARY KEY (`IDSujet`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=252 ;

CREATE TABLE IF NOT EXISTS `pv_themes` (
  `IDTheme` int(11) NOT NULL AUTO_INCREMENT,
  `NomTheme` varchar(200) NOT NULL,
  `IDPv` int(11) NOT NULL,
  `ActifTheme` int(11) NOT NULL,
  PRIMARY KEY (`IDTheme`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=6 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
